### ISSUE TITLE
Audio/Video Out of Sync for WEBDL Content with Dovi

### ISSUE THREAD

**Issue by socratesprime** [nichols89ben/Tdarr_DoVi_Processing#1]
Thanks for working on this project—it has been great!

I am currently running this in Docker on a TrueNAS Scale system.

My media primarily consists of remuxed movies and high-quality WEBDL files with Dolby Vision (DV) metadata. All movies are in MKV containers, which is why your project has been amazing for me. My current use case involves using my own set of plugins to clean the audio, clean subtitles, and extract subtitles. After that, the file is passed into the flow you shared using the "Enter from Another Flow" route. My expectation is that the final output will be an MP4 file with Dolby Vision.

It works flawlessly for all remuxed movies with DV metadata, but that is not the case for WEBDL files. In all the WEBDL examples I have tested, the final output video ends up with audio/video sync issues. Interestingly, the subtitles remain in sync with the audio, but the video is out of sync.

When I use a different method to remux the WEBDL files, everything works perfectly. So, it seems the issue is with the Dovi workflow. I can generate logs to help diagnose the problem—please let me know what you need, and how you would like me to share them.

**Comment by nichols89ben** [comment]
Are you re-encoding the file or just remuxing? Can you post the logs somewhere and the ffprobe output 

ffprobe -v error -hide_banner -print_format json -show_streams -show_format '/file/path'

**Comment by socratesprime** [comment]
My current workflow does not involve any re-encoding, only remuxing. I've included the output from the ffprobe command you shared in your comment, as well as the Tdarr job report for the same WebDL file. To generate the job report, I used the exact same DOVI flow shared on your GitHub, with no modifications made. I have confirmed that the final output file has audio/video sync issues, as described in my original post. I tested with Plex on my TV, and with VLC Media Player on windows.

As an aside, during this trial, I did notice that the subtitles were properly extracted with the year of the movie included in the name of the SRT file. Previously, I observed that the year was not included in the name, causing the media player to fail to identify the subtitles when playing the movie. I’m not sure what changed.

[dovi_webdl_report.txt](https://github.com/user-attachments/files/18862160/dovi_webdl_report.txt)

[ffprobe _output.json](https://github.com/user-attachments/files/18862196/ffprobe._output.json)

**Comment by socratesprime** [comment]
Did you have any luck replicating the issue I experienced? Is everything running smoothly for you? No hiccups at all? I've gone over my set up several times and can't figure out if I'm doing something wrong. I'd truly appreciate your help.

**Comment by nichols89ben** [comment]
user config needed updating

**Comment by socratesprime** [comment]
Can you elaborate on what you mean by > user config needed updating ? Did you find a solution to the problem?

**Comment by nichols89ben** [comment]
> Can you elaborate on what you mean by > user config needed updating ? Did you find a solution to the problem?

My bad, I helped someone on Discord with the username Shades that said they opened an issue, I thought it may have been you but it was the other one. 

Can you also post your docker compose?

**Comment by socratesprime** [comment]
Here's my docker compose:

```
services:
#    _____   ___      _     ___   ___ 
#   |_   _| |   \    /_\   | _ \ | _ \
#     | |   | |) |  / _ \  |   / |   /
#     |_|   |___/  /_/ \_\ |_|_\ |_|_\
  
  tdarr_DoVi:
    container_name: tdarr_DoVi
    privileged: true
    image: ghcr.io/haveagitgat/tdarr:2.35.02 #will need to adjusted to the latest version number if it changes
    restart: unless-stopped
    networks:
      - tdarr_network #A docker network with this same name created at the end of the Yaml below

    ports:
      - 3265:3265
      - 3266:3266
    environment:
      - TZ=America/Los_Angeles
      - PUID=568
      - PGID=568
      - webUIPort=3265
      - serverPort=3266
      - UMASK_SET=002
      - internalNode=false
      - inContainer=false
      - nodeName=Yeezy
      - ffmpegVersion=7
    volumes:
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Tdarr_Server_Storage:/app/server:rw"
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Config:/app/configs:rw"
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Tdarr_Logs_Storage:/app/logs:rw"
      - "/mnt/Prime_Pool/Media_Library:/Media_Library:rw"
      - "/mnt/Prime_Stripped_SSDs/Temp_Dataset:/Shared_TEMP:rw"

#    devices:
#      - /dev/dri:/dev/dri # This is for hardware acceleration, if you don't have a GPU, remove this line

  tdarr_DoVi-node:
    container_name: tdarr_DoVi-node
    image: nichols89ben/dovi-tdarr-node:2.35.02 #will need to adjusted to the latest version number if it changes
    restart: unless-stopped
    networks:
      - tdarr_network #A docker network with this same name created at the end of the Yaml below
    environment:
      - TZ=America/New_York
      - PUID=568
      - PGID=568
      - serverIP=tdarr_DoVi
      - webUIPort=3265 #adjust to your port
      - serverPort=3266
      - UMASK_SET=002
      - inContainer=true
      - nodeName=DoVi_Yeezy #you can change the name, but i would leave it the same as plugins would need to be adjusted
      - ffmpegVersion=7

    volumes:
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Tdarr_Server_Storage:/app/server:rw"
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Config:/app/configs:rw"
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Tdarr_Logs_Storage:/app/logs:rw"
      - "/mnt/Prime_Pool/Media_Library:/Media_Library:rw"
      - "/mnt/Prime_Stripped_SSDs/Temp_Dataset:/Shared_TEMP:rw"

#    devices:
#      - /dev/dri:/dev/dri # This is for hardware acceleration, if you don't have a GPU, remove this line

networks:
  tdarr_network:
    driver: bridge

```
