### ISSUE TITLE
Stutters or Micro-Pause During Playback of DoVi Profile 7 Files

### ISSUE THREAD

**Issue by socratesprime** [nichols89ben/Tdarr_DoVi_Processing#4]
I have quite a few 4K remux releases, and I’ve identified an issue with the ones that have Dolby Vision Profile 7. After transcoding in Tdarr, playback exhibits lag or stutter during specific scenes. This behavior is consistent—no matter how many times I start over with different remux files of the same movie, the output always stutters in the same spots. There are no audio or subtitle sync issues, just the stutters.

I’m not sure if this is an FPS issue, but I have confirmed that the stutters do not exist in the original files. I have also tested playback across different media players, including VLC, Plex on LG TV, Plex on Web, and Plex on Android. The issue persists regardless of the player used.

I've tested this with remuxed files of:

Across the Spider-Verse – during the chase where Miles dives through the cogs after speaking to Peter B. Parker.

Encanto – during the song Miracle, right before Mirabel opens the door.

So far, this has occurred in every Dolby Vision Profile 7 movie processed using the flow. All of these movies were remuxed copies. The stuttering happens frequently and can be quite distracting once noticed.

I have attached the logs for my most recent worker report and included my docker-compose.yaml below. Let me know if you need any further information.

Logs:
[42AjlmuR--log.txt](https://github.com/user-attachments/files/19408795/42AjlmuR--log.txt)

Docker-compose.yaml:

```
services:
#    _____   ___      _     ___   ___ 
#   |_   _| |   \    /_\   | _ \ | _ \
#     | |   | |) |  / _ \  |   / |   /
#     |_|   |___/  /_/ \_\ |_|_\ |_|_\
  
  tdarr_DoVi:
    container_name: tdarr_DoVi
    privileged: true
    image: ghcr.io/haveagitgat/tdarr:2.35.02 #will need to adjusted to the latest version number if it changes
    restart: unless-stopped
    networks:
      - tdarr_network #A docker network with this same name created at the end of the Yaml below

    ports:
      - 3265:3265
      - 3266:3266
    environment:
      - TZ=America/Los_Angeles
      - PUID=568
      - PGID=568
      - webUIPort=3265
      - serverPort=3266
      - UMASK_SET=002
      - internalNode=false
      - inContainer=false
      - nodeName=Yeezy
      - ffmpegVersion=7
    volumes:
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Tdarr_Server_Storage:/app/server:rw"
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Config:/app/configs:rw"
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Tdarr_Logs_Storage:/app/logs:rw"
      - "/mnt/Prime_Pool/Media_Library:/Media_Library:rw"
      - "/mnt/Prime_Stripped_SSDs/Temp_Dataset:/Shared_TEMP:rw"

#    devices:
#      - /dev/dri:/dev/dri # This is for hardware acceleration, if you don't have a GPU, remove this line

  tdarr_DoVi-node:
    container_name: tdarr_DoVi-node
    image: nichols89ben/dovi-tdarr-node:2.35.02 #will need to adjusted to the latest version number if it changes
    restart: unless-stopped
    networks:
      - tdarr_network #A docker network with this same name created at the end of the Yaml below
    environment:
      - TZ=America/New_York
      - PUID=568
      - PGID=568
      - serverIP=tdarr_DoVi
      - webUIPort=3265 #adjust to your port
      - serverPort=3266
      - UMASK_SET=002
      - inContainer=true
      - nodeName=DoVi_Yeezy #you can change the name, but i would leave it the same as plugins would need to be adjusted
      - ffmpegVersion=7

    volumes:
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Tdarr_Server_Storage:/app/server:rw"
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Config:/app/configs:rw"
      - "/mnt/NVME_Pool/Prime_APPs/Docker_Stacks/Tdarr/Tdarr_Logs_Storage:/app/logs:rw"
      - "/mnt/Prime_Pool/Media_Library:/Media_Library:rw"
      - "/mnt/Prime_Stripped_SSDs/Temp_Dataset:/Shared_TEMP:rw"

#    devices:
#      - /dev/dri:/dev/dri # This is for hardware acceleration, if you don't have a GPU, remove this line

networks:
  tdarr_network:
    driver: bridge

```
